
title: Opendoc Documentation
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-include-cache
baseurl: ''
kramdown:
  auto_id_stripping: true
section_order:
repository: opendocsg/opendoc-theme
server_PROD: https://search.opendoc.sg
server_DEV: https://search-staging.opendoc.sg
styling_options:
  primary_brand_color: '#454F5B'
  opendoc_logo_path: /assets/images/logo-full.png
  logo_path: /assets/images/logo-full.png
  feedback_url: https://form.gov.sg/5cee3d46138e3200109244df
